/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SprintResponse } from '../../models/sprint-response';

export interface FindSprintsByProject$Params {
  'project-id': number;
}

export function findSprintsByProject(http: HttpClient, rootUrl: string, params: FindSprintsByProject$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SprintResponse>>> {
  const rb = new RequestBuilder(rootUrl, findSprintsByProject.PATH, 'get');
  if (params) {
    rb.path('project-id', params['project-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SprintResponse>>;
    })
  );
}

findSprintsByProject.PATH = '/sprints/project/{project-id}';
