/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProjetTeamMemberResponse } from '../../models/projet-team-member-response';

export interface GetTeamMembers$Params {
  'projet-id': number;
}

export function getTeamMembers(http: HttpClient, rootUrl: string, params: GetTeamMembers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProjetTeamMemberResponse>>> {
  const rb = new RequestBuilder(rootUrl, getTeamMembers.PATH, 'get');
  if (params) {
    rb.path('projet-id', params['projet-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProjetTeamMemberResponse>>;
    })
  );
}

getTeamMembers.PATH = '/projets/{projet-id}/team';
