/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProjetTeamMemberResponse {
  accountLocked?: boolean;
  email?: string;
  enabled?: boolean;
  id?: number;
  nom?: string;
  prenom?: string;
}
