/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Projet {
  actif?: boolean;
  dateDebut?: string;
  dateFin?: string;
  description: string;
  id?: number;
  nom: string;
  statut?: 'EN_COURS' | 'TERMINE' | 'EN_PAUSE' | 'A_FAIRE';
}
