/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RoleResponse {
  createdDate?: string;
  id?: number;
  lastModifiedDate?: string;
  name?: string;
}
