/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProductBacklog } from '../models/product-backlog';
import { Sprint } from '../models/sprint';
import { UserStory } from '../models/user-story';
export interface SprintBacklog {
  id?: number;
  productBacklog?: ProductBacklog;
  sprints?: Array<Sprint>;
  userStories?: Array<UserStory>;
}
