/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoleResponse } from '../models/role-response';
export interface UserResponse {
  accountLocked?: boolean;
  createdDate?: string;
  dateNaissance?: string;
  email?: string;
  enabled?: boolean;
  fullName?: string;
  id?: number;
  lastModifiedDate?: string;
  nom?: string;
  prenom?: string;
  roles?: Array<RoleResponse>;
}
