/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserSummaryResponse {
  accountLocked?: boolean;
  email?: string;
  enabled?: boolean;
  fullName?: string;
  id?: number;
}
