/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRequest {
  accountLocked?: boolean;
  dateNaissance?: string;
  email: string;
  enabled?: boolean;
  nom: string;
  password?: string;
  prenom: string;
  roleIds?: Array<number>;
}
