/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getAllRoles1 } from '../fn/role-management/get-all-roles-1';
import { GetAllRoles1$Params } from '../fn/role-management/get-all-roles-1';
import { getRoleById } from '../fn/role-management/get-role-by-id';
import { GetRoleById$Params } from '../fn/role-management/get-role-by-id';
import { getUsersByRole } from '../fn/role-management/get-users-by-role';
import { GetUsersByRole$Params } from '../fn/role-management/get-users-by-role';
import { RoleResponse } from '../models/role-response';
import { UserSummaryResponse } from '../models/user-summary-response';

@Injectable({ providedIn: 'root' })
export class RoleManagementService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllRoles1()` */
  static readonly GetAllRoles1Path = '/roles';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllRoles1()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllRoles1$Response(params?: GetAllRoles1$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RoleResponse>>> {
    return getAllRoles1(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllRoles1$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllRoles1(params?: GetAllRoles1$Params, context?: HttpContext): Observable<Array<RoleResponse>> {
    return this.getAllRoles1$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<RoleResponse>>): Array<RoleResponse> => r.body)
    );
  }

  /** Path part for operation `getRoleById()` */
  static readonly GetRoleByIdPath = '/roles/{role-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRoleById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRoleById$Response(params: GetRoleById$Params, context?: HttpContext): Observable<StrictHttpResponse<RoleResponse>> {
    return getRoleById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRoleById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRoleById(params: GetRoleById$Params, context?: HttpContext): Observable<RoleResponse> {
    return this.getRoleById$Response(params, context).pipe(
      map((r: StrictHttpResponse<RoleResponse>): RoleResponse => r.body)
    );
  }

  /** Path part for operation `getUsersByRole()` */
  static readonly GetUsersByRolePath = '/roles/{role-id}/users';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUsersByRole()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsersByRole$Response(params: GetUsersByRole$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserSummaryResponse>>> {
    return getUsersByRole(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUsersByRole$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsersByRole(params: GetUsersByRole$Params, context?: HttpContext): Observable<Array<UserSummaryResponse>> {
    return this.getUsersByRole$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserSummaryResponse>>): Array<UserSummaryResponse> => r.body)
    );
  }

}
