/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { assignRoleToUser } from '../fn/user-management/assign-role-to-user';
import { AssignRoleToUser$Params } from '../fn/user-management/assign-role-to-user';
import { createUser } from '../fn/user-management/create-user';
import { CreateUser$Params } from '../fn/user-management/create-user';
import { deleteUser } from '../fn/user-management/delete-user';
import { DeleteUser$Params } from '../fn/user-management/delete-user';
import { findAllUsers } from '../fn/user-management/find-all-users';
import { FindAllUsers$Params } from '../fn/user-management/find-all-users';
import { findUserById } from '../fn/user-management/find-user-by-id';
import { FindUserById$Params } from '../fn/user-management/find-user-by-id';
import { getAllRoles } from '../fn/user-management/get-all-roles';
import { GetAllRoles$Params } from '../fn/user-management/get-all-roles';
import { PageResponseUserResponse } from '../models/page-response-user-response';
import { removeRoleFromUser } from '../fn/user-management/remove-role-from-user';
import { RemoveRoleFromUser$Params } from '../fn/user-management/remove-role-from-user';
import { Role } from '../models/role';
import { toggleUserLock } from '../fn/user-management/toggle-user-lock';
import { ToggleUserLock$Params } from '../fn/user-management/toggle-user-lock';
import { toggleUserStatus } from '../fn/user-management/toggle-user-status';
import { ToggleUserStatus$Params } from '../fn/user-management/toggle-user-status';
import { updateUser } from '../fn/user-management/update-user';
import { UpdateUser$Params } from '../fn/user-management/update-user';
import { UserResponse } from '../models/user-response';

@Injectable({ providedIn: 'root' })
export class UserManagementService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findUserById()` */
  static readonly FindUserByIdPath = '/users/{user-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findUserById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findUserById$Response(params: FindUserById$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    return findUserById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findUserById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findUserById(params: FindUserById$Params, context?: HttpContext): Observable<UserResponse> {
    return this.findUserById$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

  /** Path part for operation `updateUser()` */
  static readonly UpdateUserPath = '/users/{user-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUser$Response(params: UpdateUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    return updateUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUser(params: UpdateUser$Params, context?: HttpContext): Observable<UserResponse> {
    return this.updateUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

  /** Path part for operation `deleteUser()` */
  static readonly DeleteUserPath = '/users/{user-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteUser$Response(params: DeleteUser$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteUser(params: DeleteUser$Params, context?: HttpContext): Observable<void> {
    return this.deleteUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `findAllUsers()` */
  static readonly FindAllUsersPath = '/users';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllUsers()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllUsers$Response(params?: FindAllUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseUserResponse>> {
    return findAllUsers(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllUsers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllUsers(params?: FindAllUsers$Params, context?: HttpContext): Observable<PageResponseUserResponse> {
    return this.findAllUsers$Response(params, context).pipe(
      map((r: StrictHttpResponse<PageResponseUserResponse>): PageResponseUserResponse => r.body)
    );
  }

  /** Path part for operation `createUser()` */
  static readonly CreateUserPath = '/users';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createUser$Response(params: CreateUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    return createUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createUser(params: CreateUser$Params, context?: HttpContext): Observable<UserResponse> {
    return this.createUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

  /** Path part for operation `assignRoleToUser()` */
  static readonly AssignRoleToUserPath = '/users/{user-id}/roles/{role-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assignRoleToUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  assignRoleToUser$Response(params: AssignRoleToUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    return assignRoleToUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assignRoleToUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assignRoleToUser(params: AssignRoleToUser$Params, context?: HttpContext): Observable<UserResponse> {
    return this.assignRoleToUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

  /** Path part for operation `removeRoleFromUser()` */
  static readonly RemoveRoleFromUserPath = '/users/{user-id}/roles/{role-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeRoleFromUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeRoleFromUser$Response(params: RemoveRoleFromUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    return removeRoleFromUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeRoleFromUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeRoleFromUser(params: RemoveRoleFromUser$Params, context?: HttpContext): Observable<UserResponse> {
    return this.removeRoleFromUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

  /** Path part for operation `toggleUserStatus()` */
  static readonly ToggleUserStatusPath = '/users/{user-id}/toggle-status';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `toggleUserStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  toggleUserStatus$Response(params: ToggleUserStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    return toggleUserStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `toggleUserStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  toggleUserStatus(params: ToggleUserStatus$Params, context?: HttpContext): Observable<UserResponse> {
    return this.toggleUserStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

  /** Path part for operation `toggleUserLock()` */
  static readonly ToggleUserLockPath = '/users/{user-id}/toggle-lock';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `toggleUserLock()` instead.
   *
   * This method doesn't expect any request body.
   */
  toggleUserLock$Response(params: ToggleUserLock$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    return toggleUserLock(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `toggleUserLock$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  toggleUserLock(params: ToggleUserLock$Params, context?: HttpContext): Observable<UserResponse> {
    return this.toggleUserLock$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

  /** Path part for operation `getAllRoles()` */
  static readonly GetAllRolesPath = '/users/roles';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllRoles()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllRoles$Response(params?: GetAllRoles$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Role>>> {
    return getAllRoles(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllRoles$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllRoles(params?: GetAllRoles$Params, context?: HttpContext): Observable<Array<Role>> {
    return this.getAllRoles$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Role>>): Array<Role> => r.body)
    );
  }

}
