/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserSummaryResponse } from '../../models/user-summary-response';

export interface GetUsersByRole$Params {
  'role-id': number;
}

export function getUsersByRole(http: HttpClient, rootUrl: string, params: GetUsersByRole$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserSummaryResponse>>> {
  const rb = new RequestBuilder(rootUrl, getUsersByRole.PATH, 'get');
  if (params) {
    rb.path('role-id', params['role-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserSummaryResponse>>;
    })
  );
}

getUsersByRole.PATH = '/roles/{role-id}/users';
