/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserResponse } from '../../models/user-response';

export interface RemoveRoleFromUser$Params {
  'user-id': number;
  'role-id': number;
}

export function removeRoleFromUser(http: HttpClient, rootUrl: string, params: RemoveRoleFromUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
  const rb = new RequestBuilder(rootUrl, removeRoleFromUser.PATH, 'delete');
  if (params) {
    rb.path('user-id', params['user-id'], {});
    rb.path('role-id', params['role-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserResponse>;
    })
  );
}

removeRoleFromUser.PATH = '/users/{user-id}/roles/{role-id}';
